---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
        - name: book-catalog
          image: sit722cnpart4.azurecr.io/book-catalog
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: postgresql://cloudnative_6g97_user:XHayQE9IzHs0S4DYfvAUDxIFtVm85ZfW@dpg-crggsu88fa8c73ap95k0-a.oregon-postgres.render.com/cloudnative_6g97
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
        - name: inventory-management
          image: sit722cnpart4.azurecr.io/inventory-management
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: postgresql://cloudnative_6g97_user:XHayQE9IzHs0S4DYfvAUDxIFtVm85ZfW@dpg-crggsu88fa8c73ap95k0-a.oregon-postgres.render.com/cloudnative_6g97
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
